default:
  http_metas:
    content-type: text/html

  metas:
    title:        3tab
    robots:       index, follow
    description:  A 3-on-3 tab
    keywords:     symfony, project
    language:     en

  stylesheets:    [main]

  javascripts:    [libs/jquery-1.6.2.js, libs/tablesorter/jquery.tablesorter.js, libs/firebug/firebug.js, libs/preload.js]

  has_layout:     on
  layout:         layout
