default:
  http_metas:
    content-type: text/html

  metas:
    title:        symfony project
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [main]

  javascripts:    [libs/jquery-1.2.6.js, libs/tablesorter/jquery.tablesorter.js, libs/firebug/firebug.js, libs/preload.js]

  has_layout:     on
  layout:         layout
